"""Rename instok to instock

Revision ID: a9bcb93e05f5
Revises: f330b3c5bdeb
Create Date: 2025-02-06 00:43:34.386427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9bcb93e05f5'
down_revision = 'f330b3c5bdeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instock', sa.String(length=5), nullable=False))
        batch_op.drop_column('instok')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instok', mysql.VARCHAR(length=5), nullable=False))
        batch_op.drop_column('instock')

    # ### end Alembic commands ###
